name:                next
version:             0.0.1.0
github:              "pittma/next"
license:             MIT
author:              "dan pittman"
maintainer:          "dan@dpitt.me"
copyright:           "dan pittman, 2017"

extra-source-files:
- readme.md

synopsis:            An adventure in type-level FSMs
description:         Please see the README on Github at <https://github.com/pittma/next#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src